### ISSUE TITLE
replace jsonstream with JSONStream

### ISSUE THREAD

**Issue by dominictarr** [substack/node-browserify#1251]
NPM has confused opinions about cases of names of modules when publishing. Some operating systems are also confused by lowercase names, and the presence of JSONStream and jsonstream in the same tree is possible. However, today one bug saves us from another and npm only checks the name validation in the client! so I have published new versions of the uppercase version.

- [x] browser-pack substack/browser-pack#57
- [x] deps-sort substack/deps-sort#5
- [x] insert-module-globals substack/insert-module-globals#44
- [x] module-deps substack/module-deps#84

https://github.com/dominictarr/JSONStream/issues/68

this issue supercedes https://github.com/substack/node-browserify/pull/1247

**Comment by TheSharpieOne** [comment]
I would not depend on "npm only checks the name validation in the client".  That may change and cause dominictarr/JSONStream#68 all over again.  I'm not sure the solution, but it would more than likely involve the lower case name (as it conforms to the [confused] opinions npm has about package names).

**Comment by zertosh** [comment]
@TheSharpieOne I think it makes sense to go back to "JSONStream" as a semver patch (just like it was semver patch to go to "jsonstream"), and leave any changes in case to a semver major release.

**Comment by dominictarr** [comment]
@TheSharpieOne when npm introduced the lower case rule it did allow updates to legacy upper case modules (for better or worse) they broke that, but they have promised to fix it, so i think it is reasonable. there are currently only 8 modules that use jsonstream but > 280 that use JSONStream directly. So it's gonna be much easier to get those 8 modules to change than those 280!

**Comment by TheSharpieOne** [comment]
@dominictarr I see, as long as npm allows for support of legacy uppercase modules going forward (fixing that bug).  I would rather see npm know the difference between upper and lowercase (which may be OS related, but they can work around that).

**Comment by jmm** [comment]
@TheSharpieOne 
> I would rather see npm know the difference between upper and lowercase (which may be OS related, but they can work around that).

It doesn't sound like anything is going to happen in that department. You way want to see this issue @zertosh pointed me to: https://github.com/npm/npm/issues/7933

**Comment by zertosh** [comment]
Ok it's all published now with JSONStream as browserify@10.1.3, browser-pack@4.0.4, deps-sort@1.3.8, insert-module-globals@6.4.2, and module-deps@3.7.12.

Only browserify@10.1.2, browser-pack@4.0.3, deps-sort@1.3.7, insert-module-globals@6.4.3, and module-deps@3.7.11 ever referenced "jsonstream".
